---
editor_options: 
  markdown: 
    wrap: 72
---

# 第二讲：如何开始使用R {#lesson-2}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
##library(tidyverse) # Wickham的数据整理的整套工具
pdf.options(height=10/2.54, width=10/2.54, family="GB1") # 注意：此设置要放在最后
```

**前言**

首先，我们需要明确数据分析的出发点：解决特定问题。对于从事研究工作的同学来说，解决自己的研究问题最为重要。因此，我们需要不断思考并与导师讨论，确保问题得到明确的提出。数据分析中的技术必须为问题服务，所以问题的重要性直接关系到数据分析的实际价值。

除了用于研究，数据分析还可以解决实践中的问题，例如交通分流和辅助决策。尤其是在疫情期间，行为科学和大量的行为研究数据可以帮助政府和决策者做出正确的决策。在公司中，数据分析也有类似的应用。我们需要清晰地认识到数据分析的出发点和应用场景，这是我们所有数据分析的核心，也是最为关键的一点。我们学习这些技能的目的在于让其更加可靠和有效，能够有效地解决问题。这才是真正的根本所在，请务必不要忽略这点。

## 要解决的数据分析问题简介 {#2-data-for-lesson}

### 第一个数据 {#2-data-1}

### 第二个数据 {#2-data-2}

## 如何安装 {#2-install-R}

这节课程的主题是数据分析，这是研究生需要学习的知识。我不会在此深入探讨技术，而是开始讲解如何操作。首先是安装过程，可以在百度或必应中搜索R语言官方网站，然后在该网站中下载安装程序，该程序适用于不同的操作系统和版本。对于Windows系统而言，安装过程比较简单，但对于Mac系统，安装过程可能会稍微复杂一些。Mac系统可能会有两个版本，分别为ARM64和PKG版本。ARM64版本是一种新型的芯片架构，适用于苹果芯片的电脑。
使用本地化的中文语言安装R语言会更加方便，以避免编码问题。现在，我们开始安装R语言吧！首先，您需要下载R的安装包，您可以选择从官方网站下载，或者从国内的镜像站点，如清华镜像站。下载完成后，运行安装程序。在安装过程中，您可以选择是否自定义一些安装选项，但是默认选项通常已经足够了。最后，点击完成按钮，等待安装完成即可。安装完成后，您可以打开R语言的界面，看到官方的导航界面，其中有许多可供选择的选项。为了演示启动R语言的过程，我们将点击"Download
R"按钮。进入后，您将看到一个"R for
Windows"的基础包，下载并安装即可。为避免出现问题，请确保选择英文路径作为安装目录。完成安装之后，您可以开始实际学习操作。在此我也想提醒大家不要把安装目录放在中文文件夹里，因为我们使用的是来自国外开发者的国外软件，基本上是以英文为主的，如果使用中文可能会出现编码问题。

在上方您可以看到，此处默认选择了中文作为系统显示语言，大概是系统语言设置为中文后自动采用了中文显示。请问各位组员，现在都可以正常地看到这个界面了吗？刚刚我检查了一下，大部分的人都没有遇到任何问题，但是有一位同学看到了一些警告，猜测是语言设置引起的。对于那位出现警告的同学，可以将软件的信息全部切换到英文，允许我给大家展示一下，这是我第一次通过这种方式进行操作。以前我通常通过写代码、搜索相关软件然后在搜索框中打开软件来实现，强行改变所使用的语言环境被称为硬改。相对来说，这种方式更有效。

请问各位注意到我的操作路径了吗？它应该是在 "C盘" 的
"users"文件夹下，接着是R语言的安装目录。例如：在 "Program
Files"中。然后我们要打开文件并使用TXT工具修改文件"language"。可能需要管理员权限才能执行操作。这可能是必须的,让我再试试，如果还不行，我们就先暂停，以后再使用某些软件完成这种修改。还是不行吗？好吧，那我们来看看下一个问题。

针对另一个问题，我认为以后可能会遇到同样的情况。就是，您可能会看到一些红色警告的字体。在R语言中也会遇到这种情况。这里有两种类型的警告：一种是称为"警告（warnings）"，另一种是"错误（errors）"。对于那些被警告的代码，我们需要仔细检查，看看是否会对我们的运行造成严重的影响。如果没有明显的影响，那么就可以忽略。然后，我们可能会遇到一些问题，例如，遇到一些非UTF-8编码的语言编码。这意味着我们不是使用Unicode编码方式。为了解决这些问题，我们通常使用UTF-8编码方式，这是中文中非常常见的编码方式。在大部分计算机系统中，我们都可以使用UTF-8编码方式，因为它是国际上通用的编码方式。

## 如何方便使用？Rstudio的安装与界面介绍 {#2-Rstudio}

大家都已经成功安装了 R 语言，现在看到的是consol控制台界面。早期的
R语言使用这个控制台进行输入和操作。比如，我们可以输入一个简单的命令，例如：
a \<- 100，，在变量a中存放了一个 1 到 100
的数字序列。控制台支持用户输入任何语句，比如
demo()，来打开一个示范程序的工具窗口，显示可用的函数。控制台提供了用户与计算机交互的一个基础接口。在控制台中很多命令都可以合成更复杂的语句，比如画图命令：plot(x,
y)。这将自动打开一个窗口显示绘制的图形。

对于没有编程经验的同学来说，这个可能是一个不太熟悉的点。为什么我们在这里输入这个东西呢？为什么会跳出这个东西呢？有时候会出错吗？例如，我们输入a会得到一个数字，但是如果输入
b，他会告诉你没有这个对象，同样地，如果输入
c，也不会有任何效果。这里的一个难点是，为什么有些输入会被计算机执行，但是有些不会？还有就是，为什么有些输入会产生图形效果，有些则不会？这实际上是我们和计算机交互的一种方式，这与过去使spss软件的方式有所不同。在使用spss软件时，我们通过点击屏幕来进行交互，并从菜单中选择选项。这被称GUI，即图形用户界面。
然而，当我们使用 R
语言或其他语言时，我们主要使用的不是这种图形界面。我们只有一个输入代码的窗口，通过在这里输入代码与计算机交互。这是我们最常用、最需要的程序。对于其他语言也是一样。很少有人真正使用这种代码式的交互，因为它不太方便。在
Windows 中，也有这样一种交互方式，只需按下 Windows 键和 shift
即可。你会看到一个终端界面，它非常像以前的苹果电脑和 Mac os的 Terminal。

这样的交互方式的缺点是，我们不知道哪些变量保留在内存中。当我们进行一系列操作时，我们不知道哪些操作是我们刚才输入的。它们存在于计算机的缓存之中。如果我们输入了许多变量，如
a、b、c、d
等，我们无法回忆起这些变量的细节。因此，当我们学习R语言时，我们希望有一个更好的地方来编写代码。我们不希望一次只写一行代码，然后再运行。因此，我们需要一个更友好的代码编辑器，而不仅仅是控制台。虽然控制台是与R进行交互的窗口，但有时不够友好。
\### Rstudio的安装与界面介绍 {#2-Rstudio-install}

幸运的是，我们可以使用R Studio来完成这项任务。R
Studio与R相似，因此我们需要安装好R之后，再安装R
Studio。有两个版本可以选择：Windows版和Mac版。安装时，我们需要将其安装在非中文目录下。安装后，我们可以选择64位系统。使用R
Studio的最大好处是我们可以一次编写一长串代码，然后执行它们。

打开了R
studio之后，界面会有一些关于信息提示的内容。如果studio崩溃了，是否允许自动给你把报告发回给studio，这是一个关于隐私保护的咨询同意。点yes也没有问题。现在我们可以看到，打开RStudio后，显示出的是一个白色背景的界面，我们可以通过更改外观中的主题来改变界面颜色。在这个地方，工具中有一个全局选项，外观，你可以把它改成更专业的样式。现在界面变得专业很多了，这是我们通过调节一些参数实现的。当然，也可以根据自己的喜好来调整。另外，将界面背景改成灰色可以省些电，因为不用一直发亮光。

接下来讲讲界面的调整。我们的界面是由四个面板组成的，但是在刚安装RStuidio时，我们看到的是三个面板的界面，界面可能还有点不一样。我们可以新建一个project来呈现一个新的面板，以此方便自己的数据分析项目。我们可以首先新建一个文件夹，把数据放进去，然后点击file，选择new
project，此时会出现几个选项。我们要选择existing
directory，找到刚才新建的文件夹。创建完之后，文件夹里面会出现一个名为project的文本文件，它记录了我们的一些操作过程。注意，在windows里面，当你在c盘上进行读写的时候可能会出现一些权限问题，可以通过以管理员身份运行解决。

在这个project里，我们可以新建一个写代码的文档。在这个时候，会有一个没有命名的文件，叫做"Untitled
1"，一般情况下我们会给它命名，比如我们可以给它命名为"read
me"，作为保存项目相关信息的文件夹。我们也可以给它命名为"this is a
testing
file"。然后我们可以将它保存为txt格式，或者更好的Markdown格式，这个时候不会对代码执行产生影响。
在stuidio中，我们看到了四个窗口，这四个窗口分别是这个脚本的编辑区，控制台，环境变量以及帮助。脚本的编辑区是一个可以记录我们想写的所有代码，并且可以选择性的运行某段代码的空间。如果我们创建的是一个R脚本，就可以看到它上面有run或者其他命令选项。提示输入代码的时候，可以根据之前输入的一部分字符来预测接下来可能会输入的内容，这有助于提高代码输入效率。我们可以将代码分类放到一起，形成一个脚本文件。当我们保存
Readme 文件后，一般会将其文件后缀名命名为
R，它本质上也是一种文本文件，可以使用文本编辑器来打开。

在文件夹里，我们可以找到我们保存的 Read me文件和以 .r
结尾的测试文件，它们实际上都是以 TXT 格式存储的，我们可以用 TXT
编辑器来打开它们。但是，为了更好地写 R 语言代码，我们一般会选择用 R
Studio 软件来打开和运行这些文件。

当我们用 R Studio
打开一个文件时，我们会看到一些窗口，其中最左上角的窗口是用于编辑 R
代码的地方。在右上角，有一个包含 "environment "
的窗口，这个窗口包含了我们的工作区域，就像我们的工作记忆一样，只要我们在关闭窗口之前还没把代码移除，就会存储在这个窗口中。这个窗口实际上就是为了帮助我们更好地管理我们的变量和数据。比如，我们可以在代码中定义一个变量
a，并用简单的代码运行它。运行后，我们可以在右上角的环境窗口中看到这个变量，这就像是我们的工作记忆的一个展示口，告诉我们目前正在工作的变量和数据是什么。

此外，R Studio 还有一个 "history "
的窗口，它会记录我们输入的所有命令，这样我们就可以回放我们曾经输入的代码。我们在进行一些探索性数据分析的时候我们需要查看一些变量，那么我们就能在工作空间里面找到相应的变量。最后一个是plot
就是我们画图的界面 我们可以在这里找到我们所需的图形化展示效果。

总结一下，我们在R语言中常用的界面包括控制台、文件管理器、画图界面以及帮助界面。在控制台console中，我们可以使用R命令进行交互，使用terminal与系统进行交互。在文件管理器中，我们可以浏览我们的工作路径以及数据文件。在画图界面中，我们可以将数据以图表形式呈现。最后，在帮助界面中，我们可以查看命令的含义并获取操作帮助。

### 如何方便使用？Rstudio的安装与界面介绍 {#2-Rstudio}

现在我们打开了一个文件夹，不知道这里面有什么文件。例如，我们可以看到这个文件夹路径是C盘Users，我的用户名是OneDrive，从这里不断向下查找，因为我们打开了这个R项目，所以它会自动把这里面的文件全部关联起来。如果我们没有打开一个R项目，但是打开了一个新的搜索，就会新开一个USU的窗口，那么此时我们可以看到这个文件是不同的，它可能就是你默认的这个工作的目录。然而，在文件夹中，这个文件还有点意思，与我们想象的不太一样，我们可以自己修改一下。它默认的应该是这个Document，应该是在这个Home里，但现在它没有默认的。这个文件实际上就是你现在所在的这个工作目录的显示，这里面有什么东西就展示在这里了。

有的时候，我们想要查看文件夹中的文件时，传统的方法是用历史记录，就是把当前文件夹里面的文件全部列出来，这种方式去查看。另外一种方法就是画图，我们刚才已经画过图，可以用`plot`画一个直方图，我们将'hest'用直方图的方式来画一下。运行完这个命令后，将会看到它跳到右下角的'plot'这个地方。但是，有时候，如果文件夹中的图像比较大，它是不会显示出来的，此时你需要把窗口拉大一点，或将窗口放大，这样画出来的图像更清楚。这里的输出可以作为'PDF'，但这里面更多的是用来做展示的。我们真正想要画出那些可出版的图像还是要在代码里进行，所以我们需要熟悉使用这些界面。

其中还有一个界面我之前没有提到，那就是'packages'。在这里，可以方便地查看我们安装了哪些包。但是，包是什么我们还没有讲，之后我们会讲到。

那么我们现在先测试一下'RLM'，我们可以再测试一下后面的内容。我理解您需要我将录音稿进行润色修改，调整逻辑和句法使其更易读。我已修改后稿如下：

我们能够成功在R语言的rsgel中画出此图，这基本上说明我们的安装没有出现任何问题。我之前使用的是a，现在我将它换成了a，然后我运行了一下，这表明我们可以更加细致地对其进行定制。我画了两幅图，通过画图中的箭头，你可以看到前后两幅图之间的区别。在前面，我们使用Proad
a（黑色a）画出了这样的图，从-3到3，每一个区间为1。我们对break的调整让它变得更加细致，我们可以向前，这样的话，大家可以看到这幅图更加细致了。另外，我们前面的x和y是a，但是如果我们进行个人化定制，我们可以将其改成value。上面的图形标题也改成了normal
distribution。前面的图形标题是"his gram of
a"，所以我们已经进行了一点点的个性化。大家看能否输出这样的结果呢？如果基本上输出的话，我们就解决了第一步问题，这是用iPhone解决问题的第一步。我们成功地安装了R语言，并测试了绘图。小组长，请确保你们的小组成员已经理解这些内容，看是否有问题或疑问。能否复制电脑上的内容？如果有问题，请举手示意。我们进行这次测试的主要目的是为了避免中文用户名可能带来的问题，如果我们在USB中进行操作时，可能会出现问题。我们提醒大家在USB中选择一个命令运行时，选择"run"，他会自动运行。然而，当你将光标放在这里时，"Ctrl +
Enter"或选择"run"都可以运行。因此我们可以将一行代码分成几行，在括号内拼凑起来。只需要将光标放在代码的任何位置，按下"Ctrl+Enter"就可以运行它。在Mac下，也可以使用"Command"键+"Enter"来实现相同的效果。为了使录音稿更具可读性，以下是修改后的文本：

值得一提的是国内也有R语言社区，每年会举办不止一次的会议。该社区主要是在统计学这一领域，但也有商业公司参与支持。中文的R语言社区的合作伙伴包括统计之都和不同大学的统计学系。我做了一些修改后文本如下：
在国际上也有一个趋势，即以前大家主要关注的是任务，特别是数学方面的算法研发，但是近年来，例如R语言的开发者g
g
plus获得了统计学的大奖，说明人们越来越重视软件开发在科研和世界发展中的贡献。

讲师：大家好，欢迎来到本节课程。今天我们要讲述的是在R语言中识别代码的标点符号，特别是在初学者的第一个问题中。那我们如何输入标点符号呢？

首先，让我们看这个括号。如果我们把鼠标放在这个括号这里，你会发现后面的那个括号变化了。这表明这两个括号是一起的，选中了表示这两个括号是一起的。如果你把这个括号放在别的地方，它可能就不一样了。当我们把鼠标放在后面的时候，前面这个括号也会有一个意义。这实际上是R99帮我们很好地一个地方，当你的有明显的语法错误的时候，他立刻就给你爆出来了。

有同学刚才把逗号都删除了，虽然在语法上没有任何问题，但是最终我们在运行的时候，就会出现一个标题叫做normal
distribution。同时，我们还会发现我们多出了几个变量，比如metal、main、x
label和y label。实际上这些都是我们运行的几行独立的命令。

那我们如何避免这个问题呢？这里很重要的是标点符号，特别是我们需要知道这些符号的位置。这并不是一个很不常见的错误，实际上是一个很常见的错误。最后大家的结果可能都不一样，所以在观看别人代码的时候，需要注意这些符号的细微差别，从而避免出现这种情况。

另外，我还想提醒大家一个非常典型的问题，那就是我们通常用中文输入法，但是如果你的符号使用中文的，在R语言中可能会识别不出来。所以在输入代码的时候，最好使用英文符号。修改后文本：

这个地方存在问题。如果我选中这里的一个逗号，就会发现这是一个英文的逗号。如果我把它改成中文的逗号，他就会报错。我们可以看到，中英文的逗号差别很大。如果我把它换成一个中文的逗号，他会出现插入符，因为此时他没有识别出你这个中文的逗号，应该在这里出现一个逗号，将其与下面的内容分隔开。但是实际情况是不存在逗号，就会出现一个叉叉的符号，意味着出现错误。如果你把它换成英文的逗号之后，就没有任何的问题了。这个问题在代码编写过程中会反复出现，因为这是一个很常见的错误。

让我们回到PPT，基本上我看大家能够成功地安装好了。之后我们开始解释R的一些基本概念和术语，我们前面提到的，包括交互式代码和存储在R环境中的一些变量。正常情况下，控制台里只会出现一个a或者x，而不会出现其他的变量名。出现其他变量名的情况会在出错后发生。

这个问题也是很容易出现的。有时我们会反复使用同一变量名，并为其赋值。如果你不记得前面已经赋值过某一变量，然后你又对它进行了运算操作，这时结果有可能不是你预料的。这是一个很微妙的细节问题，后面大家会在实际操作代码过程中有所体会。

接下来，我们有个问题需要解决。有些R函数和输入的内容可以成功运行和返回结果，有些则不能。我们自然而然地问，这些"有意义"的字符或函数在R中从哪里来。例如，我们可以使用RM等命令，但也还有其他可用的命令。此外，我们也可以对两个变量进行操作。以下是修改后的文本：

现在我来简单介绍一下阿龙。他代表一个有意义而又神秘的东西。我们从正态分布里随机抽取N个数，那么这个正态分布是什么样的分布呢？比如说，第一个是0，命等于0，$SD$等于1；下面这个是命等于0.5，$SD$也等于1，这里有没有空格都无所谓。那么我们很自然就想，能不能直接输入一个叫做t-test的函数进行检验呢？然而，我们可能很容易就发现，其实并没有叫t-test的函数。我们还试了几个，但都没有发现这样的方式。而且，特别是这个第二个大学test。我们如果去看blue这个包的话，会发现他实际上是有这个函数的，并且如果我们小小的输入t点test它也是有的。那么，这就提示我们，实际上在R语言里面有一些函数是有用的，而有一些是不能用的。那么这些函数叫什么呢？一般来说，我们如果没有为他们打过标记，就称之为函数。这个函数后面一般接着一个括号，括号里面可以输入额外的东西。我们称之为这个变量verbos。那么，如果我们想要看一下t-test，我们可以输入一个小问号，然后跟上t-test。这个时候，右下角的帮助文件就会告诉我们关于t-test的一些帮助信息。如果我们看到最上面的那个，可能有的时候会忽略它，但是t-test后面跟着一个大括号是非常重要的。这个大括号后面有一个翻译叫做"curve
the
brick"，就是一个用于取到折线部分的大括号。最后，大括号后面有一个叫states的东西。这个states实际上就是一个叫做states的校验包。这里提到了一个在R语言中非常重要的概念，就是package。Package是一些模块化的方式来扩展R的功能或实现扩展。以下是修改后的文本：

R语言是一种计算机语言，它可以帮助我们完成许多工作。R语言还有许多扩展包，这些扩展包的语法与R语言相同，且功能可以超出原始的R语言基础函数。这些扩展包使得整个生态系统变得非常丰富。通常，一个扩展包包括一系列函数、数据集和文档。这些元素被组织和命名，使其方便使用。

如下图所示，中间是R语言，周围是许多R扩展包，我们将着重讲解这些方形。

函数实际上与数学中的函数相似，如f(x)。函数有一个符号以及输入和输出参数。例如，t.test(V1,V2)中，t.test是函数名，V1和V2是输入参数。在"bivariate"函数中，它有一个一串字符，其中表示函数的名称，输入参数以及变量（如x）是抽象的。当然，它可能会产生一个结果，解释输出结果。

我们将介绍各种类型的扩展包，如阿贝斯的基础包，在安装阿贝斯时会自带这些基础包，比如base。我做了如下修改：

本节课将讲解一个非常重要的主题------R语言中的包。请大家不要开启麦克风，避免噪音影响听力。

Abax包中实际上包含了非常多的方面，从a到z都有涵盖。R语言中还有众多社区共同贡献的包，目前已经有数以万计的包，其中不乏很多常用的包和具有丰富功能的包。一些常用的功能还可能整合到核心系统中。

这些包有着很强的领域特殊性。针对不同领域的方法学研究者开发的包，也可以更好地符合该领域的数据类型、视觉表达及输入习惯。比如，心理学或社会科学领域可能使用的包有BruceR，Psych或Lavaan，或者SEM。

还有一些包比较符合数据科学领域。尤其是在人工智能领域上，近10年来深度学习、自然语言处理、图像处理等方法的包也逐渐成熟。

同时，许多包也会按照统一的风格系统去开发，比如Tidyverse，并具有自己的特殊语法流程。使用这些包，代码组织更加紧凑，使用起来也更加方便。

最近也推出了一些适用于数据科学、心理学及社会科学分析的包，比如称为EasyStats的包，他提供了一个更加简约的统计分析系统，其中集成了一些主要的包，如Performance、Reports等。此外，还有一些特定的包系统，比如CRAN
Task
Views，可以把特定主题的包集合在一起，方便用户查找和查阅相关使用文档。

这里是一些跟我们所学相关的包。例如，我们在下面的课程中将学习历史趋势的预测如何进行，我们将介绍混合模型（mix
model或者沉积模型）和心理测量相（psychometrics）等等。以下是修改后的文本：

有些R包比较出名，例如reputable
research。在讨论数据分析时，我们可能会涉及一些时间序列的数据，这些数据可能与正常相关。有一些机器可以提供较好的帮助，但是这些都是在某个领域受欢迎的专门工具。这样，我们就可以把这些包集合在一起，互相参考，避免重复造轮子。还有像Cos英粉这样的包，最近也很火，但在心理学领域并不常用。

当我们想要安装这些包时，我们可以使用install
packages这个命令并加上包的名字（注意需要加双引号）。install
packages本身是一个函数，如果我们不加双引号，会使其找不到这个名字的包，因为他会把它当成变量，在工作区中寻找。如果没有找到变量，就会报错。而且，当我们需要安装多个包时，我们可以逐个安装它们，例如GGPR2。

接下来，我们可以在packages中查看我们已安装的包。我们还可以借助tools进行安装。在此过程中，如果我们从原始源中安装包，会弹出一个窗口使我们选择下载方式。国内的用户一般会选择清华的镜像来加速下载。另一种方法是直接在代码中设置，例如使用getOption和repos指令来设置下载地址。
