---
title: "R语言在心理学研究中的应用: 从原始数据到可重复的论文手稿"
author: "胡传鹏"
date: "2023年1月5日"
site: bookdown::bookdown_site
output: bookdown::gitbook
description: "课程bookdown"
documentclass: book
classoption: oneside
biblio-style: apa
bibliography: [mybib.bib]
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 教学内容与课时{#0-index}

## 目录

第一讲：为什么要学习R（3学时）\
1.1 R在心理科学及社会科学中的运用\
1.2 R语言使用的示例展示\
1.3 课程安排\
1.4 如何学好这门课\

第二讲：如何开始使用R:（3学时）\
2.1 要解决的数据分析问题简介[介绍我们的数据和拟解决的问题，对比R和传统flow]\
2.1 如何安装？\
2.2 如何方便使用？Rstudio的安装与界面介绍\

第三章：如何导入数据（3学时）\
3.1 路径与工作目录\
3.2 读取数据\
3.3 了解R里的数据 （R语言中的对象）\

第四章：如何清理数据一 R语言编程基础（3学时）\
4.1 R对象的操控\
4.2 逻辑运算\
4.3 函数\

第五章：如何清理数据二 数据的预处理（3学时）\
5.1 数据预处理准备\
5.2 数据预处理的基本操作\
5.3 数据预处理的进阶操作\

第六章：如何探索数据: 描述性统计与数据可视化基础（3学时）\
6.1 描述性统计\
6.2 ggplot2的基本使用\
6.3 ggplot2的元素控制\

第七章：如何进行基本的数据分析: t-test和anova（3学时）\
7.1 语法实现\
7.2 分析的流程\

第八章：如何进行基本的数据分析: 相关与回归（3学时）\
8.1 语法实现\
8.2 分析的流程\

第九章：如何进行基本的数据分析: 中介分析（3学时）\
9.1 语法实现\
9.2 分析的流程\

第十章：结果稳健吗？使用Multiverse比较方法选择对结果的影响（3学时）\
10.1. 多种分析方法的实现\
10.2 代码整合与规范化\

第十一章: 如何得到可发表的图像: 数据可视化进阶（3学时）\
11.1 ggplot2的图层与面板控制\
11.2 ggplot2与其他工具的结合\

第十二章：从分析到手稿（3学时）\
12.1 Rmarkdown\
12.2 Latex语法基本介绍\
12.3 papaja工具包的介绍\

第十三章：多人协作版本控制:Git？（3学时）\
13.1 版本控制与git\
13.2 多人协作与git\

第十四章：如何帮助我们计划下一个研究？（3学时）\
14.1 计算效应量：Meta-analysis\
14.2 计划样本量：Power analysis （模拟）\
14.3 计划分析方法：假数据与分析代码（模拟）\
14.4 并行处理\

第十五章：如何让导师/合作者完全重复我的分析？（3 学时）\
15.1 软件版本记录\
15.2 容器技术与docker的使用\
