---
title: "R语言在心理学研究中的应用: 从原始数据到可重复的论文手稿(V2)"
author: "胡传鹏(等)"
date: "`r format(Sys.Date(), '%Y年%m月%d日')`"
site: bookdown::bookdown_site
output: bookdown::gitbook
description: "课程bookdown"
documentclass: book
classoption: oneside
biblio-style: apa
bibliography: [mybib.bib]
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 引言 {-}

本电子书通过[`bookdown`](https://bookdown.org/)进行创建。文字与代码是对本人2024年春季学期的《R语言在心理研究中应用》一课录音的整理而。文字稿由本人与志愿者以志愿方式进行整理，因此，可能存在如下问题：

-   文字口语化严重
-   图片或者文献引用不全
-   错别字等
-   代码错误

望读者朋友多多包涵。欢迎有兴趣有能力的朋友多多批评指正。如果您觉得这个电子书有用，可以给我们的github repo加一个🌟，这是对我们持续开源的巨大鼓励！\

本课相关资源也完全开源，链接如下：[课件](https://github.com/hcp4715/R4Psy)、[B站录频](https://space.bilibili.com/252509184/channel/collectiondetail?sid=2314135)、[本电子书代码](https://github.com/hcp4715/R4PsyBook)。\

本套课程及资源会在每年春季学期更新，欢迎大家多多批评指正。提出问题的最佳方式：在本电子书的GitHub仓库的[issues](https://github.com/hcp4715/R4PsyBook/issues)中开新的issue。\
参与贡献方式：见下面《如何帮助完善本书》这一小节。

## 开放电子书的初衷
分享知识，向众多开源的电子书作者致敬，为中文网络世界中的R语言相关教材略尽绵薄之力。

## 如何帮助完善本书
可以参考[这个英文的教程](https://neuropsychology.github.io/NeuroKit/resources/contributing.html#how-to-use-github-to-contribute)，我们进行了大致的翻译！

可能需要的前期知识：(1) 如何使用github;(2) 如何使用[bookdown](https://bookdown.org/)。

大致可以分成如下几步：

第一，创建github账号，然后fork这个项目。\
第二，将fork后的项目clone到您自己的电脑上。\
第三，在自己的电脑上使用Rstudio打开`Book`这个文件夹中的`Book.Rproj`，完善您觉得需要完善的内容。*\
第四，将修改后的内容push到您的github上。\
第五，在github上提交pull request。\


\* 本项目的文件夹结构如下，内容修改主要在`Book`这个子文件夹下的`100*-lesson*_2024.rmd`文件。

```
.
├── Book
│   ├── 1001-lesson1_2024.Rmd
│   ├── 1002-lesson2_2024.Rmd
│   ├── 1003-lesson3_2024.Rmd
│   ├── 1004-lesson4_2024.Rmd
│   ├── 1005-lesson5_2024.Rmd
│   ├── 1006-lesson6_2024.Rmd
│   ├── 1007-lesson7_2024.Rmd
│   ├── 1008-lesson8_2024.Rmd
│   ├── 1009-lesson9_2024.Rmd
│   ├── 1010-lesson10_2024.Rmd
│   ├── 1011-lesson11_2024.Rmd
│   ├── 1012-lesson12_2024.Rmd
│   ├── 1013-lesson13_2024.Rmd
│   ├── 1014-lesson14_2024.Rmd
│   ├── 1015-lesson15_2023.Rmd
│   ├── 1016-lesson16_2023.Rmd
│   ├── 1017-lesson17_2023.Rmd
|   ├── ...
|
│   ├── data
│   │   ├── Template_Folder_System_Empirical_Chuan-Peng_Lab
│   │   ├── Template_Folder_System_Meta_Chuan-Peng_Lab
│   │   ├── match
│   │   └── penguin
│
├── LICENSE.md
├── R4PsyBook.Rproj
└── README.md
```
## 使用许可

本电子书使用CC4.0作为使用许可，如果您使用本电子书内容，请规范引用。

## 目录

第一讲：为什么要学习R\
1.1 R在心理科学及社会科学中的运用\
1.2 R语言使用的示例展示\
1.3 课程安排\
1.4 如何学好这门课\

第二讲：如何开始使用R\
2.1 要解决的数据分析问题简介[介绍我们的数据和拟解决的问题，对比R和传统flow]\
2.1 如何安装？\
2.2 如何方便使用？Rstudio的安装与界面介绍\

第三章：如何使用本课件/电子书资源\
3.1 Git与Github\
3.2 项目、文件与代码的规范化\

第四章：如何导入数据\
4.1 路径与工作目录\
4.2 读取数据\
4.3 了解R里的数据 （R语言中的对象）\

第五章：如何清理数据一 R语言编程基础 \
5.1 R对象的操控\
5.2 逻辑运算\
5.3 函数\

第六章：如何清理数据二 数据的预处理 \
6.1 Tidyverse简介\
6.2 问卷数据的预处理:基本 \
6.3 实验数据的预处理:提高 \

第七章：探索数据: 描述性统计与数据可视化基础\
7.1 描述性统计\
7.2 探索性数据分析(DataExplorer)\
7.3 ggplot2基础\

第八章：R语言中的统计分析: 线性模型1 (*t*-test、anova等) \
8.1 语法实现\
8.2 分析的流程\

第九章：R语言中的统计分析: 线性模型2(rm-anova、层级模型)\
9.1 语法实现\
9.2 分析的流程\

第十章：R语言中的统计分析: 线性模型3(GLM)\
10.1 语法实现\
10.2 分析的流程\

第十一章：R语言中的统计分析: 线性模型4(中介效应模型)\
11.1. 多种分析方法的实现\
11.2 代码整合与规范化\

第十二章: 如何得到可发表的图像: 数据可视化进阶（3学时）\
12.1 ggplot2的图层与面板控制\
12.2 ggplot2与其他工具的结合\

第十三章：心理学研究中的网络分析 \

第十四章：心理学元分析入门 \

第十五章：补充1:如何进行基本的数据分析：相关与回归 \

第十六章：补充2:从分析到手稿 \

第十七章：补充3:效应量与元分析 \
